services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: knockknock
      POSTGRES_PASSWORD: knockknock
      POSTGRES_DB: knockknock
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
